### PR TITLE
Update shared.lua

### PR DESCRIPTION
**Pull request by Mesrine67**
change `Lang:t` > `locale`

## Description

change of the glass translation system to that of ox_lib

### CODE REVIEW

**Comment by KostaZx** [comment]
When making changes, do not create new pr. Instead, add commits to your existing pr

**Comment by Mesrine67** [comment]
> When making changes, do not create new pr. Instead, add commits to your existing pr

how do we do ? I don't know how to do it

**Comment by KostaZx** [comment]
> > When making changes, do not create new pr. Instead, add commits to your existing pr
> 
> 
> 
> how do we do ? I don't know how to do it

just create pr after you finish converting everything

**Comment by KostaZx** [comment]
@Mesrine67 I'll close all the pull requests you've created, and you'll need to create a new one that includes all your made changes.

**Pull request closed without merging**
