### PR TITLE
Update main.lua | Enabled Hotkeys

### PR DESCRIPTION
**Pull request by zlexif**
Enabled hotkeys for inventory after player revival.

## Checklist

- [ x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by mafewtm** [comment]
This shouldn't be needed as inventory hotkeys are never disabled

**Comment by mafewtm** [comment]
All three of these PRs should just be one PR. There's no need to separate them based on the file you edit when they all are part of the same feature/improvement.

**Comment by Manason** [comment]
Echoing this, please combine the 3 into 1.

**Comment by zlexif** [comment]
> All three of these PRs should just be one PR. There's no need to separate them based on the file you edit when they all are part of the same feature/improvement.

im a bit slow lol havent used github in a while i tried combining them but i didnt know how ngl, ill search it up

**Comment by mafewtm** [comment]
You combine them by closing two of the prs and recommitting the changed from those to this one with an updated title, description, etc

**Pull request closed without merging**
